### ISSUE TITLE
Tags button build 404 url

### ISSUE THREAD

**Issue by abelsromero** [EclipseFdn/asciidoc-wg.eclipse.org#63]
**Describe the bug**
Project tags generate an URL (ie. http://{domain}/technology_types/java/) that does not exists.
For example the following project
![image](https://user-images.githubusercontent.com/5781153/116300531-47badf80-a79f-11eb-9445-1e31cc03d98a.png)
Has `Java` tag which points to `https://{domain}technology_types/java/`.

**To Reproduce**
1. Add new project with content
```yml
---
Title: Eclipse Austen
license: Eclipse Public License 2.0
is_incubated: true
website: https://projects.eclipse.org/proposals/eclipse-austen
github: https://myrepo.com
technology_types: [Java]
---
A description.
```
2. Build preview accorfing to instructions in README (currently: `npm install && hugo server --destination=public`)
3. Go to `http://localhost:1313/projects/`
4. Click on the tag
5. 404 screen

**Expected behavior**
At least not to fail.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Linux 5.11.14-1-MANJARO
 - Browser: Firefox
 - Version: 88.0 64bits

**Smartphone (please complete the following information):**
n/a

**Additional context**
https://asciidoc-wg.eclipse.org/technology_types/java/ also returns a 404.
